<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="panda">

<xacro:arg name="hand" default="false" />
<xacro:arg name="gazebo" default="true" />
<xacro:include filename="$(find franka_description)/robots/panda/panda.urdf.xacro"/>


 <link name="brush">        
      <origin pose="0 0 0 0 0 0"/>
        <!--<inertial mass="1.0">
          <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
        </inertial>-->

        <collision name="brush_collision">
          <geometry>
            <cylinder radius="0.003" length="0.125"/>
          </geometry>
        </collision>

        <visual name="visual">
          <geometry>
            <cylinder radius="0.003" length="0.125"/>
          </geometry>
       </visual>
          
 </link>
  <joint name="brush_to_EE" type="fixed">
      <parent link="panda_link7"/>
      <child link="brush"/>
      <origin  xyz="0.0 0.0 0.125" rpy="0.0 0.0 0.0"/> 
  </joint>      

 <!--<link name="brush"/>-->
<!--  <link name="world"/>-->
<!--  <joint name="panda_link0_to_world" type="fixed">-->
<!--      <parent link="panda_link0"/>-->
<!--      <child link="world"/>-->
<!--      <origin  xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>-->
<!--  </joint>-->
<!--  <joint name="brush_to_EE" type="fixed">
      <parent link="panda_link8"/>
      <child link="brush"/>
      <origin  xyz="0.0 0.0 0.125" rpy="0.0 0.0 0.0"/> 
  </joint> -->

  <xacro:property name="table_x" value="0.6"/>
  <xacro:property name="table_y" value="0.5"/>
  <xacro:property name="table_z" value="0.001"/>

  <link name="table_link">
    <visual>
      <origin xyz="-${table_x/3} 0 -${table_z/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${table_x} ${table_y} ${table_z}"/>
      </geometry>
      <color rgba="0.5 0.0 0.0 0.5"/>
    </visual>
    <collision>
      <origin xyz="-${table_x/3} 0 -${table_z/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${table_x} ${table_y} ${table_z}"/>
      </geometry>
    </collision>
  </link>
  
  <link name="left_margin">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="1.0 0.001 1.0"/>
      </geometry>
      <color rgba="0.5 0.0 0.0 0.5"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="1.0 0.001 1.0"/>
      </geometry>
    </collision>
  </link>
  
  <link name="right_margin">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="1.0 0.001 1.0"/>
      </geometry>
      <color rgba="0.5 0.0 0.0 0.5"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="1.0 0.001 1.0"/>
      </geometry>
    </collision>
  </link>
  
  <link name="upper_margin">
    <visual>
      <origin xyz="-${table_x/3} 0 -${table_z/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${table_x} ${table_y} ${table_z}"/>
      </geometry>
      <color rgba="0.5 0.0 0.0 0.5"/>
    </visual>
    <collision>
      <origin xyz="-${table_x/3} 0 -${table_z/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${table_x} ${table_y} ${table_z}"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="table_to_world" type="fixed">
      <parent link="world"/>
      <child link="table_link"/>
      <origin  xyz="${2*table_x/3} 0.0 -${table_z/2}" rpy="0.0 0.0 0.0"/> 
  </joint>
  
  <joint name="right_margin_to_table" type="fixed">
      <parent link="world"/>
      <child link="right_margin"/>
      <origin  xyz="${table_x/2} ${table_y/2 - 0.09} ${0.5-0.0565}" rpy="0.0 0.0 0.0"/>
  </joint>
  
  <joint name="left_margin_to_table" type="fixed">
      <parent link="world"/>
      <child link="left_margin"/>
      <origin  xyz="${table_x/2} -${table_y/2 - 0.09} ${0.5-0.0565}" rpy="0.0 0.0 0.0"/>
  </joint>
  
  <joint name="upper_margin_to_table" type="fixed">
      <parent link="world"/>
      <child link="upper_margin"/>
      <origin  xyz="${2*table_x/3} 0.0 ${2*table_y-0.0965}" rpy="0.0 0.0 0.0"/>
  </joint>
</robot>


